// src/components/Counter.tsx
import React, { useState } from 'react';
import { useStore } from '@nanostores/react';
import { count } from '../count';

export default function Counter() {
  // Declare a new state variable, which we'll call "count"
  const $count = useStore(count);

  return (
    <div className='react-component'>
      <p>You clicked {$count} times</p>
      <button onClick={() => count.set($count + 1)}>
        Click me
      </button>
    </div>
  );
}

// src/components/Counter.vue
<template>
  <div>
    {{$count}}
  </div>
  <button @click="() => count.set($count + 1)">
    + 1
  </button>
</template>

<script setup lang="ts">
import { count } from '../count'
import { useStore } from '@nanostores/vue'

import { ref } from 'vue';

const $count = useStore(count)
</script>

<style scoped>

</style>
